---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install some linux packages
      package:
        name:
          - htop
          - tmux

    - name: Copy wallpaper files
      copy:
        src: files/png/mountains.png
        dest: /usr/share/backgrounds/ansible-mountains.png
        owner: root
        group: root

    - name: Set the wallpaper
      become_user: quabid
      dconf:
        key: '/org/gnome/desktop/background/picture-uri'
        value: "'file:///usr/share/backgrounds/ansible-mountains.png'"

    - name: Set wallpaper position
      become_user: quabid
      dconf:
        key: '/org/gnome/desktop/backound/picture-uri'
        value: "'zoom'"

    - name: Copy .bashrc file
    copy:
      src: files/bashrc
      dest: ~/.bashrc
      owner: $USERNAME
      group: $USERNAME

    - name: Copy .profile file
    copy:
      src: files/profile
      dest: ~/.profile
      owner: $USERNAME
      group: $USERNAME

    - name: Copy bin scripts
    copy:
      src: files/bin
      dest: ~/bin
      owner: $USERNAME
      group: $USERNAME